name: polyquiz
description: A new Flutter project.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"  # Updated Dart SDK constraints

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Ensure you use a version that supports null safety
  socket_io_client: ^2.0.0  # Ensure you use a version that supports null safety
  shared_preferences: ^2.1.0
  intl: ^0.17.0
  instant: ^0.5.1
  timezone: ^0.9.4
  fl_chart: ^0.69.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # Add assets here if any
