export namespace PopUpMessage {
    export const LEAVE_MESSAGE = 'POP_UP_MESSAGE.LEAVE_MESSAGE';
    export const DELETE_MESSAGE = 'POP_UP_MESSAGE.DELETE_MESSAGE';
    export const DELETE_FRIEND_MESSAGE = 'POP_UP_MESSAGE.DELETE_FRIEND_MESSAGE';
    export const DELETE_QUIZ_MESSAGE = 'POP_UP_MESSAGE.DELETE_QUIZ_MESSAGE';
}
