const frenchTextValues = {
  "LOGIN_PAGE": {
    "TITLE": "Connecter",
    "SUBTITLE": "Connectez-vous à votre compte",
    "EMAIL_LABEL": "Courriel",
    "EMAIL_PLACEHOLDER": "Saisissez votre adresse courriel",
    "EMAIL_REQUIRED": "L'adresse courriel est requise.",
    "EMAIL_INVALID": "L'adresse courriel n'est pas valide.",
    "EMAIL_FORMAT_INVALID": "Le format de l'adresse courriel est invalide. Ex: utilisateur@exemple.com",
    "PASSWORD_LABEL": "Mot de passe",
    "PASSWORD_PLACEHOLDER": "Entrez votre mot de passe",
    "PASSWORD_REQUIRED": "Le mot de passe est requis.",
    "PASSWORD_MIN_LENGTH": "Le mot de passe doit avoir au moins 6 caractères",
    "SUBMIT_BUTTON": "Se Connecter",
    "NO_ACCOUNT": "Pas de compte?",
    "REGISTER_LINK": " S'inscrire",
    "SUCCESS_LOGIN_POPUP": "Connexion réussie",
    "USER_ALREADY_CONNECTED": "Cet utilisateur est déjà connecté.",
    "INVALID_EMAIL": "L'adresse e-mail est invalide.",
    "INVALID_CREDENTIAL": "Courriel et/ou mot de passe incorrect",
    "USER_DISABLED": "Le compte de cet utilisateur est désactivé.",
    "USER_NOT_FOUND": "Aucun utilisateur trouvé avec cet e-mail.",
    "WRONG_PASSWORD": "Le mot de passe est incorrect.",
    "EMAIL_ALREADY_IN_USE": "Ce courriel est déjà utilisé par un autre compte.",
    "WEAK_PASSWORD": "Le mot de passe est trop faible.",
    "OPERATION_NOT_ALLOWED": "Cette opération n'est pas autorisée.",
    "NETWORK_REQUEST_FAILED": "La connexion au réseau a échoué.",
    "REQUIRES_RECENT_LOGIN": "Veuillez vous reconnecter avant d'effectuer cette opération.",
    "UNKNOWN_ERROR": "Une erreur inconnue s'est produite.",
    "OFFLINE_PLAY":"Jouer hors-ligne"
  },
  "REGISTER_PAGE": {
    "TITLE": "S'inscrire",
    "SUBTITLE": "Créez un compte",
    "USERNAME_LABEL": "Nom d'utilisateur",
    "USERNAME_PLACEHOLDER": "Saisissez votre nom d'utilisateur",
    "USERNAME_REQUIRED": "Le nom d'utilisateur est requis.",
    "USERNAME_INVALID": "Le nom d'utilisateur ne peut contenir que des lettres et des chiffres.",
    "EMAIL_LABEL": "Courriel",
    "EMAIL_PLACEHOLDER": "Saisissez votre adresse courriel",
    "EMAIL_REQUIRED": "L'adresse courriel est requise.",
    "EMAIL_INVALID": "L'adresse courriel n'est pas valide.",
    "EMAIL_FORMAT_INVALID": "Le format de l'adresse courriel est invalide. Ex: utilisateur@exemple.com",
    "PASSWORD_LABEL": "Mot de passe",
    "PASSWORD_PLACEHOLDER": "Entrez votre mot de passe",
    "PASSWORD_REQUIRED": "Le mot de passe est requis.",
    "PASSWORD_MIN_LENGTH": "Le mot de passe doit avoir au moins 6 caractères",
    "SUBMIT_BUTTON": "S'inscrire",
    "ALREADY_HAVE_ACCOUNT": "Déjà un compte?",
    "LOGIN_LINK": " Se connecter",
    "SUCCESS_REGISTER_POPUP": "Compte créé",
    "THE_NAME_IS_ALREADY_USED": "Le nom \"{{name}}\" est déjà utilisé"
  },
  "MAINPAGE": {
    "WELCOME": "Bienvenue",
    "JOIN_GAME": "Joindre une partie",
    "CREATE_GAME": "Créer une partie",
    "ADMIN_GAMES": "Administrer les jeux",
    "SHOP": "Magasiner"
  },
  "HEADER": {
    "TOOLTIP_FRIENDS": "Amis"
  },
  "PROFILE": {
    "LEVEL": "Niveau",
    "PRESTIGE": "Prestige",
    "CURRENCY": "Argent",
    "STATISTICS": "Statistiques",
    "GAMES_PLAYED": "Parties Jouées",
    "GAMES_WON": "Parties Gagnées",
    "AVG_CORRECT_ANSWERS": "Bonnes Réponses Par Partie",
    "AVG_GAME_TIME": "Temps Moyen Par Partie",
    "SECONDS": "secondes",
    "ACHIEVEMENTS": "Exploits",
    "CONNECTION_HISTORY": "Historique des Connexions",
    "LOGIN": "Connexion",
    "LOGOUT": "Déconnexion",
    "GAME_HISTORY": "Historique des Parties",
    "WIN": "Gagné",
    "LOSS": "Perdu",
    "GAME_MODE_CLASSIC": "Classique",
    "GAME_MODE_TEAM": "Équipe",
    "SCORE": "Score",
    "GAMEMODE": "Mode de jeu",
    "GAMEMODE_CLASSIC": "Classique",
    "GAMEMODE_TEAM": "Équipe",
    "ALL_ACHIEVEMENTS": [
      "Gagner une partie en ligne",
      "Gagner une partie en équipe",
      "Gagner 5 parties",
      "Gagner 10 parties",
      "Atteindre le prestige bronze",
      "Atteindre le prestige argent",
      "Atteindre le prestige or",
      "Atteindre le prestige platine"
    ],
    "NONE": "Aucun",
    "BRONZE": "Bronze",
    "SILVER": "Argent",
    "GOLD": "Or",
    "PLATINUM": "Platine"
  },
  "FRIENDS": {
    "TITLE": "Amis",
    "PENDING_TITLE": "en attente",
    "ADD_FRIEND": "Ajouter",
    "FRIENDS_TAB": "Amis",
    "EMPTY_FRIENDS_LIST": "Votre liste d'amis est vide pour le moment.",
    "PENDING_REQUESTS_TAB": "Demandes Reçues",
    "NO_PENDING_REQUESTS": "Vous n'avez reçu aucune demande d'ami.",
    "REMOVE_FRIEND": "Supprimer un ami",
    "ACCEPT_REQUEST": "Accepter",
    "DECLINE_REQUEST": "Refuser",
    "ALREADY_SENT_ERROR": "La requête d'ami a déja été envoyée"
  },
  "AVATAR_MODIFICATION": {
    "TITLE": "Modification d'avatar",
    "CHOOSE_AVATAR": "Choisissez votre avatar",
    "UPLOAD_OWN": "Ou télécharger votre propre avatar",
    "SELECT_IMAGE": "Choisir une image",
    "CANCEL": "Annuler",
    "CONFIRM": "Confirmer",
    "SUCCESS_POPUP": "Avatar modifié avec succès",
    "ERROR": "Erreur de modification"
  },
  "USERNAME_MODIFICATION": {
    "TITLE": "Modification du nom d'utilisateur",
    "NEW_USERNAME": "Nouveau nom d'utilisateur",
    "PLACEHOLDER": "Entrer un nouveau nom d'utilisateur",
    "CANCEL": "Annuler",
    "CONFIRM": "Confirmer",
    "LETTERS_NUMBERS_ONLY": "Le nom d'utilisateur ne peut contenir que des lettres et des chiffres.",
    "MAXIMUM_10_CHAR": "Le nom d'utilisateur peut contenir au plus 10 caractères.",
    "SUCCESSFUL_MODIFICATION": "Nom d’utilisateur modifié avec succès.",
    "ALREADY_USED": "Ce nom est déja utilisé.",
    "ERROR": "Erreur de modification."
  },
  "USER_SEARCH": {
    "TITLE": "Recherche d'utilisateurs...",
    "PLACEHOLDER": "Rechercher un utilisateur",
    "TOOLTIP_SEND_REQUEST": "Envoyer une requête d'ami",
    "TOOLTIP_PENDING_REQUEST": "Demande déjà envoyée"
  },
  "SHOPPING": {
    "CURRENCY": "Argent",
    "THEMES": "Thèmes",
    "NO_THEMES": "Aucun thème disponible pour le moment.",
    "IMAGES": "Images",
    "NO_IMAGES": "Aucune image disponible pour le moment.",
    "OWNED": "Déjà possédé",
    "NOT_ENOUGH_FUNDS": "Pas assez de fonds",
    "BUY": "Acheter",
    "COST_SUFFIX": "\$",
    "CLAIM" : "réclamer",
    "CLAIMED": "réclaméé",
  },
  "GAME_ADMIN": {
    "TITLE": "Panneau d'administration : gérer tous les jeux-questionnaires",
    "QUIZZES": "Jeux",
    "LAST_MODIFIED": "Dernière Modification",
    "NO_QUIZZES": "Aucun jeu-questionnaire disponible pour le moment.",
    "REFRESH": "Rafraîchir",
    "ADD": "Ajouter",
    "IMPORT": "Importer",
    "PLAY_TOOLTIP": "Veuillez sélectionner un quiz",
    "PLAY": "Jouer",
    "TOOLTIP_EXPORT": "Exporter le questionnaire",
    "TOOLTIP_EDIT": "Modifier le questionnaire",
    "TOOLTIP_DELETE": "Supprimer le questionnaire",
    "REFRESH_FEEDBACK": "Les quiz ont été actualisés.",
    "JSON_IMPORT_FORMAT_ERROR": "Erreur : le fichier JSON est mal formaté.({{ error }})",
    "IMPORT_ERROR_HEADER_TEXT": "Le fichier que vous tenter d'importer contient le(s) problème(s) suivant(s):",
    "QUIZ_DELETED": "Ce quiz a été supprimé, veuillez choisir un autre.",
    "QUIZ_INVISIBLE": "Ce quiz est maintenant caché, veuillez choisir un autre.",
  },
  "QUIZ_SELECTION": {
    "PAGE_TITLE": "Sélectionnez un des jeux disponibles :",
    "DESCRIPTION": "Description",
    "DURATION": "Durée",
    "DURATION_SUFFIX": "s",
    "QUESTIONS": "Questions"
  },
  "QUIZ_CREATION": {
    "TITLE_CREATION": "Création du jeu",
    "TITLE_EDIT": "Modification du jeu",
    "VISIBILITY": "Visibilité",
    "PUBLIC": "Public",
    "PRIVATE": "Privé",
    "CREATOR": "Créateur",
    "TITLE_LABEL": "Titre",
    "TITLE_PLACEHOLDER": "Entrez le titre du jeu",
    "TITLE_REQUIRED": "Le titre est requis",
    "TITLE_PATTERN": "Le titre ne doit pas être composé uniquement d'espaces",
    "DURATION_LABEL": "Durée",
    "DURATION_PLACEHOLDER": "Entrez la durée (secondes) de chaque question",
    "DURATION_REQUIRED": "La durée est requise",
    "DURATION_RANGE": "La durée doit être entre 10 et 60 secondes",
    "DESCRIPTION_LABEL": "Description",
    "DESCRIPTION_PLACEHOLDER": "Entrez la description du jeu",
    "DESCRIPTION_REQUIRED": "La description est requise",
    "DESCRIPTION_PATTERN": "La description ne doit pas être composée uniquement d'espaces",
    "CREATE": "Créer",
    "EDIT": "Modifier",
    "CANCEL": "Annuler",
    "GAME_NO_LONGER_EXISTS": "Ce jeu n'existe plus.",
    "GAME_PRIVATED": "Ce jeu a été défini comme privé par le créateur et ne peut pas être modifié/exporté/supprimé.",
    "QUIZ_DELETED_BY_OTHER_USER": "Ce quiz a été supprimé par un autre utilisateur.",
    "QUIZ_VISIBILITY_CHANGED_TO_PRIVATE": "La visibilité de ce quiz a été modifiée à privée par le propriétaire pendant l'édition.",
    "TITLE_ALREADY_EXISTS": "Le titre existe déjà",
    "QUIZ_UPDATED_SUCCESS": "Le quiz a été mis à jour avec succès",
    "QUIZ_ADDED_SUCCESS": "Le quiz a été ajouté avec succès",
    "QUESTION_LIST": {
      "ADD_QUESTION": "Ajouter une question",
      "MODIFY_QUESTION": "Modifier la question",
      "MOVE_DOWN": "Déplacer la question vers le bas",
      "MOVE_UP": "Déplacer la question vers le haut.",
      "DELETE_QUESTION": "Supprimer la question",
      "QUESTION_LABEL": "Question",
      "QUESTION_TYPE_LABEL": "Type de la question",
      "QUESTION_TYPE_REQUIRED": "Le type de question est requis",
      "QUESTION_TEXT_LABEL": "Texte de la question",
      "QUESTION_TEXT_PLACEHOLDER": "Saisissez le texte de la question",
      "QUESTION_TEXT_REQUIRED": "Le texte est requis",
      "QUESTION_TEXT_PATTERN": "Le texte ne doit pas être composé uniquement d'espaces.",
      "QUESTION_POINTS_LABEL": "Le nombre de points de la question",
      "QUESTION_POINTS_PLACEHOLDER": "Entrez le nombre de points",
      "QUESTION_POINTS_REQUIRED": "Le nombre de points est requis",
      "QUESTION_POINTS_INVALID": "Le nombre de points doit être entre 10 et 100 et être un multiple de 10",
      "IMAGE_OPTIONAL": "Image (optionnel)",
      "IMAGE_CHOOSE": "Choisir une image",
      "IMAGE_PREVIEW_ALT": "Aperçu de l'image",
      "IMAGE_DELETE": "Supprimer",
      "IMAGE_SIZE_ERROR": "La taille de l'image ne doit pas dépasser 2 MB.",
      "CHOICES": "Choix :",
      "ADD_CHOICE": "Ajouter un choix",
      "ANSWER_INTERVAL": "Intervalle de réponse:",
      "MINIMUM": "Minimum",
      "MAXIMUM": "Maximum",
      "MAX_LESS_THAN_MIN_ERROR": "La valeur maximale doit être supérieure ou égale à la valeur minimale.",
      "MIN_INTEGER_ERROR": "Le minimum doit être un nombre entier.",
      "MIN_REQUIRED": "Le minimum est requis.",
      "MAX_INTEGER_ERROR": "La maximum doit être un nombre entier.",
      "MAX_REQUIRED": "La maximum est requis.",
      "MAX_TOO_LARGE": "La valeur maximale est trop grande (plus que 15 chiffres)",
      "MIN_TOO_LARGE": "La valeur minimale est trop grande (plus que 15 chiffres)",
      "MAX_TOO_SMALL": "La valeur maximale est trop petite (plus que 15 chiffres)",
      "MIN_TOO_SMALL": "La valeur minimale est trop petite (plus que 15 chiffres)",
      "CORRECT_ANSWER": "Bonne réponse :",
      "ENTER_CORRECT_ANSWER": "Entrez la valeur de la bonne réponse",
      "ANSWER_OUT_OF_RANGE": "La réponse doit être entre les bornes spécifiées.",
      "ANSWER_INTEGER_ERROR": "La réponse doit être un nombre entier.",
      "ANSWER_TOO_LARGE": "La valeur de la réponse est trop grande (plus que 15 chiffres)",
      "ANSWER_TOO_SMALL": "La valeur de la réponse est trop petite (plus que 15 chiffres)",
      "TOLERANCE_MARGIN": "Marge de tolérance :",
      "ENTER_MARGIN": "Entrez la marge de tolérance",
      "TOLERANCE_MARGIN_TOO_LARGE": "La marge de tolérance doit être au maximum 25 % de l'intervalle",
      "TOLERANCE_MARGIN_REQUIRED": "La marge de tolérance est requise.",
      "TOLERANCE_MARGIN_MIN_ERROR": "La marge doit être un nombre entier supérieure ou égale à 0.",
      "VALID_INTERVAL_MESSAGE": "L'intervalle de bonne réponse est :",
      "CHOICE": {
        "CHOICE": "Choix",
        "MOVE_DOWN": "Déplacer le choix vers le bas",
        "MOVE_UP": "Déplacer le choix vers le haut",
        "ADD_CHOICE": "Ajouter un choix",
        "REMOVE_CHOICE": "Supprimer le choix",
        "TEXT_REQUIRED": "Le texte est requis",
        "TEXT_PLACEHOLDER": "Texte du choix",
        "TRUE": "Vrai",
        "FALSE": "Faux"
      },
      "QUESTION_SUMMARY": {
        "QUESTION": "Question",
        "QUESTION_TYPE": "Type de la question",
        "QUESTION_CONTENT": "Contenu de la question",
        "QUESTION_POINTS": "Points",
        "QUESTION_IMAGE": "Image",
        "CHOICES": "Choix",
        "CHOICE": "Choix",
        "TRUE": "Vrai",
        "FALSE": "Faux",
        "INTERVAL": "Intervalle",
        "MIN": "Min",
        "MAX": "Max",
        "CORRECT_ANSWER": "Bonne réponse",
        "MARGIN_OF_ERROR": "Marge de tolérance"
      },
      "CONFIRM_QUESTION": "Confirmer",
      "SAVE_QUESTION_TOOLTIP": "Sauvegarder la question",
      "ADD_QUESTION_BUTTON": "Ajouter une question"
    }
  },
  "GAME_CONFIG_DIALOG": {
    "CONFIGURE_GAME": "Configurer la partie",
    "GAME_TYPE_LABEL": "Type de partie",
    "CLASSIC": "Classique",
    "TEAM": "Équipe",
    "PRICE_LABEL": "Prix",
    "FRIENDS_ONLY_LABEL": "Amis Seulement",
    "PRIVATE_GAME_LABEL": "Partie privée",
    "MIN_PRESTIGE_LABEL": "Prestige minimum",
    "NONE": "Aucun",
    "BRONZE": "🥉Bronze",
    "SILVER": "🥈Argent",
    "GOLD": "🥇Or",
    "PLATINUM": "🏅Platine",
    "CANCEL_BUTTON": "Annuler",
    "CREATE_GAME_BUTTON": "Créer partie",
    "GAME_TYPE_REQUIRED": "Le type de partie est requis. Veuillez sélectionner un type.",
    "PRICE_INVALID": "Le prix doit être un entier supérieur ou égal à 0.",
    "PRESTIGE_REQUIRED": "Le prestige minimum est requis. Veuillez sélectionner un prestige minimum."
  },
  "WAITING_ROOM_PAGE": {
    "TITLE": "Salle d'attente",
    "ROOM_CODE": "Code",
    "ROOM_STATUS": "La salle est",
    "STATUS_LOCKED": "verrouillée",
    "STATUS_UNLOCKED": "ouverte",
    "LOCK_ROOM_TOOLTIP": "Verrouiller la salle",
    "PLAYERS_TITLE": "Joueurs:",
    "BAN_TOOLTIP": "bannir",
    "NO_PLAYERS": "Aucun joueur présent",
    "TEAMS_TITLE": "Équipes:",
    "TEAM_LABEL": "Équipe",
    "JOIN_TEAM": "Rejoindre",
    "NO_TEAMS": "Aucune équipe présente",
    "START_BUTTON": "Commencer",
    "CREATE_TEAM": "Créer Équipe",
    "QUIZ_STARTING_IN": "Quiz commence dans :"
  },
  "POP_UP_MESSAGE": {
    "LEAVE_MESSAGE": "Êtes-vous sûr de vouloir quitter?",
    "DELETE_MESSAGE": "Êtes-vous sûr de vouloir supprimer?",
    "DELETE_FRIEND_MESSAGE": "Êtes-vous sûr de vouloir supprimer cet ami?",
    "DELETE_QUIZ_MESSAGE": "Êtes-vous sûr de vouloir supprimer ce quiz?",
    "ERRORS_DETECTED": "Erreurs détectées",
    "CLOSE": "Fermer"
  },
  "BUTTON": {
    "QUIT": "Quitter",
    "DELETE": "Supprimer"
  },
  "CONFIRMATION_DIALOG": {
    "WARNING": "Attention!",
    "CANCEL": "Annuler",
    "CONFIRM": "Confirmer"
  },
  "PLAYER_WAITING_PAGE": {
    "JOIN_PUBLIC_GAME": "Rejoindre Jeu Public",
    "JOIN_PRIVATE_GAME": "Rejoindre Jeu Privé",
    "ROOM_CODE_PROMPT": {
      "ENTER_CODE_MESSAGE": "Veuillez saisir le code de 4 chiffres fourni par l'organisateur",
      "ENTER_CODE_LABEL": "Saisir le code:",
      "ERROR_MESSAGE": "Code invalide",
      "VALIDATE_BUTTON": "Valider",
      "CANCEL_BUTTON": "Quitter",
      "JOIN_SUCCESS_MESSAGE": "Parfait! Vous pouvez rejoindre la partie",
      "BANNED_MESSAGE": "Vous avez été banni de cette partie par l'hôte!",
      "ROOM_LOCKED_MESSAGE": "Désolé! La partie est verrouillée.",
      "JOIN_BUTTON": "Rejoindre"
    },
    "ROOM_CODE_PROMPT_ERRORS": {
      "GAME_NOT_FOUND": "Il n'y a aucune partie correspondant à ce code.",
      "FRIENDS_ONLY": "Cette partie est exclusive aux amis de l'hôte.",
      "INSUFFICIENT_PRESTIGE": "Vous n'avez pas le prestige minimum pour rejoindre cette partie.",
      "INSUFFICIENT_FUNDS": "Vous n'avez pas assez d'argent pour rejoindre cette partie.",
      "BANNED_USER": "Vous avez été banni de cette partie par l'hôte.",
      "ROOM_LOCKED": "La salle est actuellement verrouillée.",
      "VALIDATION_CODE_ERROR": "Votre code doit contenir seulement 4 chiffres (ex: 1234)"
    }
  },
  "ACTIVE_GAME_LIST": {
    "PUBLIC_GAME_LIST": "Liste des parties publiques",
    "MINIMUM_PRESTIGE": "Prestige minimum",
    "FRIENDS_ONLY": "Amis seulement",
    "FRIENDS_AND_OTHERS": "Amis et autres",
    "GAME_MODE": "Mode de jeu",
    "CLASSIC": "Classique",
    "TEAM": "Équipe",
    "FREE": "Gratuit",
    "ONGOING_GAME": "Partie en cours",
    "NO_GAMES_AVAILABLE": "Aucune partie disponible",
    "CANCEL": "Annuler",
    "EXCLUSIVE_FRIENDS_GAME": "Cette partie est exclusive aux amis de l'hôte.",
    "INSUFFICIENT_PRESTIGE": "Vous n'avez pas le prestige minimum pour rejoindre cette partie.",
    "INSUFFICIENT_FUNDS": "Vous n'avez pas assez d'argent pour rejoindre cette partie.",
    "USER_BANNED": "Vous avez été banni de cette partie.",
    "ROOM_LOCKED": "La partie est actuellement verrouillée.",
    "UNKNOWN": "Quiz inconnu",
    "FAILED_TO_JOIN" : "Échec de la connection a la salle: "
},
  "PROFILE_POPUP": {
    "ACHIEVEMENTS": "Exploits",
    "ALREADY_FRIENDS_TOOLTIP": "Déjà amis",
    "SEND_FRIEND_REQUEST_TOOLTIP": "Envoyer une requête d'ami",
    "REQUEST_PENDING_TOOLTIP": "Demande déjà envoyée",
    "PRESTIGE": "Prestige",
    "CURRENCY": "Argent",
    "GAMES_PLAYED": "Parties Jouées",
    "GAMES_WON": "Parties Gagnées",
    "AVG_CORRECT_ANSWERS": "Bonnes Réponses par Partie",
    "AVG_GAME_TIME": "Temps Moyen par Partie",
    "SECONDS": "secondes"
  },
  "CHAT_COMPONENT": {
    "CHAT": "Clavardage",
    "ADD_CHANNEL": "Ajouter un Canal",
    "JOIN_CHANNEL": "Joindre un Canal",
    "MY_CHANNELS": "Mes canaux",
    "CHANNELS": "Canaux",
    "CHANNEL_CREATION": "Création canal",
    "CHANNEL_DELETION": "Suppression canal",
    "BACK": "Retour",
    "CREATE": "Créer",
    "DELETE": "Supprimer",
    "ENTER_MESSAGE": "Saisir un message...",
    "ENTER_CHANNEL_NAME": "Saisir un nom de canal...",
    "SEARCH_CHANNEL": "Chercher un canal...",
    "CHANNEL_NAME_REQUIRED": "Le nom de canal est requis.",
    "CHANNEL_NAME_PATTERN": "Le nom du canal doit seulement contenir des caractères alphanumériques.",
    "CHANNEL_NAME_MAX_LENGTH": "Le nom du canal doit contenir 20 caractères maximum.",
    "MESSAGE_MAX_LENGTH": "Le message doit contenir un maximum de 200 caractères",
    "CHANNEL_DELETED": "Le canal a été effacé. Veuillez quitter. Au revoir!",
    "DELETE_WARNING": "Attention !!!",
    "DELETE_CONFIRMATION": "Cette action est irreversible. Le canal {{channelName}} sera effacé à jamais.",
    "ROOM_IN_NAME_UNALLOWED": "Le nom de canal ne peut pas contenir: room. Veuillez choisir un autre nom.",
    "ROOM_NAME_ALREADY_USED": "Le nom {{canalName}} est déjà utilisé. Veuillez choisir un autre nom."
  },
  "AVATAR_CLICK_MENU": {
    "PROFIL": "Profil",
    "DISCONNECT": "Déconnexion"
  },
  "IMPORT_ERRORS": {
    "CHOICE_LABEL": "Choix",
    "TITLE_REQUIRED": "Le titre est requis",
    "DESCRIPTION_REQUIRED": "La description est requise",
    "INVALID_DURATION": "La durée doit être comprise entre 10 et 60 secondes",
    "MINIMUM_NUMBER_OF_QUESTIONS_REQUIRED": "Le quiz devrait contenir au moins une question",
    "TEXT_REQUIRED": "le texte est requis",
    "QUESTION_POINTS_REQUIRED": "les points d'une question sont requis",
    "INVALID_POINTS": "les points doivent être entre 10 et 100",
    "NON_DIVISIBLE_BY_TEN": "les points de la question doivent être divisible par 10",
    "INVALID_NUMBER_OF_CHOICES": "doit avoir au moins deux choix et au plus quatre choix",
    "INVALID_CHOICE": "un choix doit être soit vrai soit faux",
    "INVALID_QUESTION_CHOICES": "on doit au moins avoir une bonne réponse et une mauvaise réponse",
    "TITLE_MAX_LENGTH": "Le titre doit contenir au maximum 100 caractères",
    "DESCRIPTION_MAX_LENGTH": "La description doit contenir au maximum 250 caractères",
    "DESCRIPTION_ONLY_SPACES": "La description ne doit pas être composée uniquement d'espaces",
    "TITLE_ONLY_SPACES": "Le titre ne doit pas être composé uniquement d'espaces",
    "QUESTION_TEXT_MAX_LENGTH": "le texte de la question doit contenir au maximum 250 caractères",
    "UNSUPPORTED_QUESTION_TYPE": "ce type de question n'est pas supporté",
    "INTEGER_ANSWER_REQUIRED": "la réponse doit être un nombre entier",
    "INTEGER_MARGIN_REQUIRED": "la marge doit être un nombre entier",
    "INTEGER_INTERVAL_REQUIRED": "les intervalles doivent être des nombres entiers",
    "ANSWER_WITHIN_LIMITS": "la réponse doit être entre",
    "MINIMUM_WITHIN_LIMITS": "le minimum doit être entre",
    "MAXIMUM_WITHIN_LIMITS": "le maximum doit être entre",
    "QRE_ANSWER_REQUIRED": "la réponse est requise pour les questions de type QRE",
    "QRE_INTERVAL_REQUIRED": "l'intervalle min et max sont requis pour les questions de type QRE",
    "QRE_MARGIN_REQUIRED": "la marge est requise pour les questions de type QRE",
    "MIN_LESS_THAN_MAX": "l'intervalle min doit être inférieur ou égal à max",
    "MARGIN_NON_NEGATIVE": "la marge de tolérance doit être 0 ou plus",
    "SCIENTIFIC_NOTATION_NOT_ALLOWED": "ne doit pas être en notation scientifique",
    "ANSWER_OUTSIDE_INTERVAL": "la réponse doit être inclus dans l'intervalle",
    "MAX_MARGIN_LIMIT": "la marge doit être au maximum",
    "INTERVAL_25_PERCENT_LIMIT": "(25% de l'intervalle)",
    "CHOICE_TEXT_MAX_LENGTH": "le texte du choix doit contenir au maximum 50 caractères"
  },
  "GAME_INTERFACE": {
    "TIMER_TEXT": {
      "TIME_LEFT": "Temps restant ",
      "FINAL_RESULT": "Résultats finaux s'afficherons dans ",
      "RESULT_AVAILABLE_IN": "Résultat dans ",
      "NEXT": "Prochaine question dans ",
      "LOADING_QUESTIONS": "En attente des questions...",
    },
    "QRE_HISTOGRAM_X_VAL": {
      "WITHIN_MARGIN": "Dans l'intervalle",
      "EXACT_ANSWER": "Exacte",
      "INCORRECT_ANSWER": "Incorrecte"
    },
    "TOOLTIP": {
      "TOOLTIP_PLAY": "Jouer",
      "TOOLTIP_PAUSE": "Pause",
      "TOOLTIP_PANIC_MODE": "Activez le mode panique !",
      "TOOLTIP_PANIC_MODE_DISABLED": "Vous ne pouvez plus activer le mode panique."
    },
    "QUESTION_INFO": {
      "VALUE": "Valeur"
    },
    "QRL_CORRECTION": {
      "QUESTION_CORRECTION": "Correction de la question:",
      "PLAYER": "Joueur :",
      "ANSWER": "Réponse :",
      "SELECT_SCORE": "Veuillez sélectionner une note",
      "SCORES_TITLE": "Notes des joueurs:",
      "NAME": "Nom",
      "SCORE": "Note",
      "VALIDATE": "Valider"
    },
    "HISTOGRAM": {
      "LEGEND_HEADER": "Légende de l'histogramme:",
      "CORRECT_ANSWERS": "Bonnes réponses",
      "INCORRECT_ANSWERS": "Mauvaises réponses",
      "INACTIVE": "Inactif",
      "ACTIVE": "Actif",
      "NEXT": "Suivant",
      "PREVIOUS": "Précédent"
    },
    "PLAYER_LIST": {
      "LEGEND_TITLE": "Légende de la liste des joueurs:",
      "QUIT_TEAMMATE_LABEL": "Quitté",
      "INACTIVE": "Inactif",
      "INTERACTION": "Interaction",
      "VALIDATION": "Validation",
      "QUIT": "Quitter",
      "GAME_END": "Fin de partie",
      "SORT_BUTTONS": {
        "SORT_BY_NAME": "Nom",
        "SORT_BY_SCORE": "Point",
        "SORT_BY_STATUS": "Statut",
        "TOOLTIP_SORT_BY_NAME": "Trier par nom",
        "TOOLTIP_SORT_BY_SCORE": "Trier par point",
        "TOOLTIP_SORT_BY_STATUS": "Trier par statut",
        "TOOLTIP_CHANGE_ORDER": "Changer l'ordre"
      },
      "COLUMN_TITLES": {
        "NAME": "Nom",
        "POINTS": "Points",
        "BONUS": "Bonus",
        "TEAM": "Équipe"
      }
    },
    "PLAYER_QRL_INTERFACE": {
      "CHARACTERS_REMAINING": "Caractères restants: ",
      "ZERO_POINTS": "Vous avez eu aucun point pour votre réponse : ",
      "HALF_POINTS": "Vous avez eu la moitié des points pour votre réponse : ",
      "FULL_POINTS": "Félicitations, vous avez eu tout les points de la question pour votre réponse : ",
      "AWAITING_EVALUATION": "L'organisateur est en train d'évaluer votre réponse"
    },
    "PLAYER_QRE_INTERFACE": {
      "TOLERANCE": "Tolérance",
      "YOUR_ANSWER_INTERVAL": "Votre intervalle de réponse est:",
      "GOOD_ANSWER_WAS": "La bonne réponse était:"
    },


    "NEXT_QUESTION": "Prochaine question",
    "SHOW_RESULT": "Montrer résultat",
    "GAME_FINISHED": "Partie terminée!",
    "FINAL_SCORE": "Votre score final :",
    "PLAYERS_RESULT": "Résultats des joueurs:",
    "CURRENT_POINTS": "Pointage",
    "BONUS_RECEIVED_FEEDBACK": "Vous avez recu des points Bonus!",
    "VALIDATE_BUTTON": "Valider"
  }
};
